# Generated by Django 4.2.7 on 2023-12-16 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Eductaiondetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=150)),
                ('year', models.PositiveIntegerField(default=0)),
                ('userdet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.userside')),
            ],
        ),
    ]
